name: Deploy to AWS with terraform

on:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-check:
    name: Terraform format check
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::986527150290:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init -input=false
      - name: Format check
        run: terraform fmt -check

  terraform-plan:
    name: Plan terraform deployments
    runs-on: ubuntu-latest
    needs: terraform-check

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::986527150290:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform plan
        run: terraform plan -no-color -input=false

  terraform-apply:
    name: Apply terraform deployments
    runs-on: ubuntu-latest
    needs: [terraform-check, terraform-plan]

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::986527150290:role/GithubActionsRole
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init -input=false
      - name: Terraform apply
        run: terraform apply -auto-approve -input=false
